name: Linting

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run yamllint
        run: yamllint -s .github/workflow-templates/*

      - name: Run cfn-lint
	      run: cfn-lint -r $(AWS_DEFAULT_REGION) -t .github/workflow-templates/*
