name: Linting

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: install yamllint
        run: sudo apt-get install yamllint

      - name: where am i?
        run: ls 

      - name: Workspace
        run: echo $GITHUB_WORKSPACE

      - name: HOME
        run: echo $HOME

      - name: Run yamllint
        run: yamllint -s ./workflow-templates/mantalus-organization-ci.yaml

      - name: Install Python3 
        run: sudo apt-get install python3

      - name: Install cfn-lint
        run: pip install cfn-lint  

      - name: Run cfn-lint
        run: cfn-lint -r $(AWS_DEFAULT_REGION) -t ansible/roles/*/files/*.yaml

